const yourname = prompt("Your Name:")
document.write(`<p class="title">` + yourname + `'s Anthem</p>`)

let verb1 = prompt('Write a verb:')
let noun1 = prompt('Write a noun:')
let adverb = prompt('Write an adverb:')
let verb2 = prompt('Write a verb(past tense):')
let noun2 = prompt('Write a noun(plural):')
let noun3 = prompt('Write another noun(plural):')
let adjective1 = prompt('Write an adjective:')
let noun4 = prompt('Write another noun(plural):')
let verb3 = prompt('Write a verb(with an -ing ending):')
let color = prompt('Write your favorite color:')
let noun5 = prompt('Write another noun(plural):')
let noun6 = prompt('Write another noun:')
let noun7 = prompt('Write another noun:')
let interjection = prompt('Write an interjection:')
let adjective2 = prompt('Write another adjective:')
let verb4 = prompt('Write another verb:')
let adjective3 = prompt('Write another adjective:')
let adjective4 = prompt('Write another adjective:')

document.write(`<p class="anthem"> O say can you <span class="variables">${verb1}</span> by the dawn's early <span class="variables">${noun1}</span>, What so <span class="variables">${adverb}</span> we <span class="variables">${verb2}</span> at the twilight's last gleaming, Whose broad <span class="variables">${noun2}</span> and bright <span class="variables">${noun3}</span> through the <span class="variables">${adjective1}</span> fight, O'er the <span class="variables">${noun4}</span> we watched, were so gallantly <span class="variables">${verb3}</span>? And the rockets' <span class="variables">${color}</span> glare, the <span class="variables">${noun5}</span> bursting in <span class="variables">${noun6}</span>, Gave proof through the nught that our <span class="variables">${noun7}</span> was still there; <span class="variables">${interjection}</span> does that <span class="variables">${adjective2}</span> banner yet <span class="variables">${verb4}</span>, O'er the land of the <span class="variables">${adjective3}</span> and the home of the <span class="variables">${adjective4}</span>?`)